name: Print Xcode Version

on:
  push:
    branches:
      - main

jobs:
  print-xcode-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11
          - macos-12
          - macos-13
          - macos-14
    steps:
      - name: Print Xcode Version
        run: xcodebuild -version
      - name: Print OS Version
        run: sw_vers -productVersion
